"""The aftereffects pipeline: validated request -> isolated AE authoring ->
aerender -> ProRes 4444 master + VP9 alpha review -> verification -> reopen
check -> project bundle + manifest. Host-agnostic: RealHost drives After
Effects, FakeHost stands in where AE is absent (tests, this PC today).

Every path the pipeline touches lives under `workspace` (one attempt of one
job). Asset paths are handed in already staged inside workspace/inputs by the
caller, and are re-checked here to be inside it.
"""
import hashlib
import json
import os
import secrets
import shutil
import sys
import time
import zipfile

_WORKER_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _WORKER_DIR not in sys.path:
    sys.path.insert(0, _WORKER_DIR)

import proc  # noqa: E402
from aftereffects import fonts, media, schema  # noqa: E402
from aftereffects.errors import AEError  # noqa: E402

RECIPES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "recipes")
PHASES = ("validating", "preflight", "authoring", "rendering", "encoding", "verifying", "inspecting", "bundling")
# Progress budget per phase (fractions of 0..1), roughly by measured cost.
_BUDGET = {"validating": (0.00, 0.02), "preflight": (0.02, 0.04), "authoring": (0.04, 0.20),
           "rendering": (0.20, 0.70), "encoding": (0.70, 0.86), "verifying": (0.86, 0.93),
           "inspecting": (0.93, 0.97), "bundling": (0.97, 1.00)}


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def recipe_files(recipe):
    r = schema.RECIPES[recipe]
    return [fn for fn in ("lib.jsx", r["author"], r["revise"]) if fn]


def recipe_revision(recipe):
    """12 hex chars over lib.jsx + the recipe's author (and revise) scripts."""
    h = hashlib.sha256()
    for fn in recipe_files(recipe):
        with open(os.path.join(RECIPES_DIR, fn), "rb") as f:
            h.update(fn.encode() + b"\0" + f.read() + b"\0")
    return h.hexdigest()[:12]


def _inside(root, path):
    r = os.path.realpath(root)
    p = os.path.realpath(path)
    return p == r or p.startswith(r + os.sep)


class _Ctx:
    def __init__(self, workspace, host, log, cancel_check, deadline, progress, phase):
        self.workspace = workspace
        self.host = host
        self.log = log
        self.cancel_check = cancel_check
        self.deadline = deadline
        self._progress = progress
        self._phase = phase
        self.pids = []
        self.timings = {}
        self.current = None

    def remaining(self):
        left = self.deadline - time.monotonic()
        if left <= 0:
            raise proc.TimedOut("job deadline reached")
        return left

    def phase(self, name):
        if self.cancel_check():
            raise proc.Canceled()
        self.current = name
        self.log(f"phase {name}")
        self._phase(name)
        self._progress(_BUDGET[name][0])

    def progress(self, frac):
        lo, hi = _BUDGET[self.current]
        self._progress(lo + (hi - lo) * max(0.0, min(1.0, frac)))

    def pid_sink(self, pid, image):
        self.pids.append((pid, image))
        with open(os.path.join(self.workspace, "pids.json"), "w", encoding="utf-8") as f:
            json.dump(self.pids, f)

    def timed(self, name, fn):
        t0 = time.monotonic()
        try:
            return fn()
        finally:
            self.timings[name + "_s"] = round(time.monotonic() - t0, 3)


def _write_job_jsx(ctx, stage, recipe_file, job):
    """job.jsx = the validated job object as a literal + lib + recipe. JSON is
    valid ExtendScript for these types; nothing from the request is code."""
    path = os.path.join(ctx.workspace, "project", f"{stage}.jsx")
    lib = os.path.join(RECIPES_DIR, "lib.jsx")
    recipe = os.path.join(RECIPES_DIR, recipe_file)
    manifest = job["manifest_path"]
    with open(path, "w", encoding="utf-8") as f:
        f.write("// generated by worker/aftereffects/pipeline.py - do not edit\n")
        f.write("$.global.AE_JOB = " + json.dumps(job, ensure_ascii=True) + ";\n")
        f.write("try {\n")
        f.write(f"  $.evalFile(new File({json.dumps(lib)}));\n")
        f.write(f"  $.evalFile(new File({json.dumps(recipe)}));\n")
        f.write("} catch (e) {\n")
        f.write(f"  var __f = new File({json.dumps(manifest)}); __f.encoding = 'UTF-8';\n")
        f.write("  if (__f.open('w')) { __f.write('{\"ok\":false,\"stage\":\"bootstrap\",\"error\":{\"code\":\"JSX_ERROR\",\"message\":' + "
                "'\"' + String(e.message).replace(/\\\\/g,'\\\\\\\\').replace(/\"/g,'\\\\\"') + '\",\"line\":' + (e.line||0) + '}}'); __f.close(); }\n")
        f.write("  app.quit();\n}\n")
    return path


def _run_stage(ctx, stage, recipe_file, job):
    manifest_path = job["manifest_path"]
    job = dict(job, token=secrets.token_hex(16))
    jsx = _write_job_jsx(ctx, stage, recipe_file, job)
    m = ctx.host.run_script(stage, job, jsx, manifest_path, ctx.remaining(), ctx.cancel_check, ctx.pid_sink)
    if not isinstance(m, dict):
        raise AEError("AE_NO_MANIFEST", f"{stage} manifest is not an object")
    if not m.get("ok"):
        err = m.get("error") or {}
        code = err.get("code") if err.get("code") in __import__("aftereffects.errors", fromlist=["CODES"]).CODES else "JSX_ERROR"
        where = f" ({os.path.basename(str(err.get('file', recipe_file)))}:{err.get('line', '?')})" if err.get("line") is not None else ""
        at = f" at step '{m['step']}'" if m.get("step") else ""
        raise AEError(code, f"{stage} script failed{where}{at}: {err.get('message', 'no message')}",
                      {"jsx_line": err.get("line"), "jsx_file": err.get("file"), "stage": stage, "step": m.get("step")})
    return m


def _stage_assets(ctx, request, assets_local):
    """Confirm every request asset is a staged file inside workspace/inputs."""
    staged = {}
    for a in request["assets"]:
        p = assets_local.get(a["name"])
        if not p or not os.path.isfile(p):
            raise AEError("ASSET_MISSING", f"asset {a['name']!r} was not staged")
        if not _inside(os.path.join(ctx.workspace, "inputs"), p):
            raise AEError("INVALID_REQUEST", f"asset {a['name']!r} is outside the job workspace")
        digest = sha256_file(p)
        if a.get("sha256") and digest != a["sha256"]:
            raise AEError("ASSET_HASH_MISMATCH", f"asset {a['name']!r}: sha256 {digest[:12]} != declared {a['sha256'][:12]}")
        entry = {"path": os.path.abspath(p), "sha256": digest, "size": os.path.getsize(p), "kind": a["kind"]}
        if _is_svg(p):
            png = os.path.splitext(os.path.abspath(p))[0] + ".rasterized.png"
            _, (w, h) = media.rasterize_svg(p, png, ctx.remaining(), ctx.cancel_check, ctx.log)
            ctx.log(f"  asset {a['name']}: SVG rasterized to {w}x{h} PNG for After Effects")
            entry.update(path=png, rasterized_from={"path": os.path.abspath(p), "sha256": digest, "width": w, "height": h})
        staged[a["name"]] = entry
    return staged


def _is_svg(path):
    if os.path.splitext(path)[1].lower() == ".svg":
        return True
    try:
        with open(path, "rb") as f:
            head = f.read(512).lstrip()
        return head.startswith(b"<svg") or (head.startswith(b"<?xml") and b"<svg" in head)
    except OSError:
        return False


def _preflight_fonts(request):
    wanted = sorted({t["font"] for t in schema.text_layers(request)})
    miss = fonts.missing(wanted)
    if miss:
        raise AEError("FONT_MISSING", f"font(s) not installed on this host: {', '.join(miss)}",
                      {"missing_fonts": miss})
    return wanted


def _encode_and_verify(ctx, request, rendered, out_dir, name, render_info=None):
    comp = request["settings"]["composition"]
    render_info = render_info or {}
    master = os.path.join(out_dir, f"{name}-master.mov")
    review = os.path.join(out_dir, f"{name}-review.webm")
    sheet = os.path.join(out_dir, f"{name}-contact.png")

    ctx.phase("encoding")
    src_info = {}
    if os.path.isfile(rendered):
        has_alpha, pix, codec = media.source_has_alpha(rendered)
        src_info = {"kind": "mov", "pix_fmt": pix, "codec": codec}
        if not has_alpha:
            raise AEError("ALPHA_MISSING", f"aerender output {os.path.basename(rendered)} is {codec}/{pix}: the "
                          f"output module template '{ctx.host.om_template}' does not write RGB+Alpha")
        src_args = ["-i", rendered]
        n_src = media.count_frames(rendered)
    else:
        src_args, n_src = media.sequence_inputs(rendered, comp["fps"])
        src_info = {"kind": "sequence", "files": n_src}
    if n_src != comp["frames"]:
        raise AEError("RENDER_INCOMPLETE", f"aerender produced {n_src} frames, expected {comp['frames']}")
    # AE's "Lossless with Alpha" writes premultiplied (matted with black) RGBA;
    # the master is delivered STRAIGHT so ffmpeg/browser overlays composite
    # without dark fringes. Straight sources pass through untouched.
    premult = (render_info.get("alpha") == "premultiplied")
    vf = media.UNPREMULTIPLY_VF if premult else None
    src_info["alpha_from_ae"] = render_info.get("alpha")
    src_info["unpremultiplied"] = premult
    src_info["aerender"] = {k: render_info.get(k) for k in ("format", "channels", "depth", "output_to")}
    ctx.timed("encode_master", lambda: media.encode_prores4444(src_args, master, comp["fps"], ctx.remaining(),
                                                                ctx.cancel_check, ctx.log, vf=vf))
    # The intermediate is huge (1.2 GB of raw BGRA for 5 s at 1080x1920); it has
    # served its purpose once the master exists and is verified below.
    _drop_intermediate(rendered, ctx.log)
    ctx.progress(0.6)
    ctx.timed("encode_review", lambda: media.encode_vp9_alpha(master, review, ctx.remaining(), ctx.cancel_check, ctx.log))
    ctx.progress(1.0)

    ctx.phase("verifying")
    checks = ctx.timed("verify", lambda: media.verify_master(master, comp, out_dir, ctx.remaining(), ctx.cancel_check, ctx.log))
    ctx.progress(0.7)
    ctx.timed("contact_sheet", lambda: media.contact_sheet(master, sheet, comp["frames"], ctx.remaining(), ctx.cancel_check, ctx.log))
    review_info = ctx.timed("verify_review", lambda: media.verify_review(review, comp["frames"] // 2))
    checks["source"] = src_info
    return {"master": master, "review": review, "contact_sheet": sheet, "checks": checks, "review_info": review_info}


def _drop_intermediate(rendered, log):
    try:
        if os.path.isfile(rendered):
            size = os.path.getsize(rendered)
            os.remove(rendered)
            log(f"  removed intermediate {os.path.basename(rendered)} ({size} bytes)")
        else:
            import glob
            n = 0
            for f in glob.glob(rendered):
                os.remove(f)
                n += 1
            log(f"  removed {n} intermediate frames")
    except OSError as e:
        log(f"  could not remove intermediate render: {e}")


def _inspect(ctx, request, project_path, out_dir, expect_texts):
    ctx.phase("inspecting")
    job = {"manifest_path": os.path.join(out_dir, "inspect-manifest.json"), "project_path": project_path,
           "composition": request["composition"]}
    m = ctx.timed("inspect", lambda: _run_stage(ctx, "inspect", "inspect_project.jsx", job))
    comp = m.get("comp") or {}
    layers = comp.get("layers") or []
    by_name = {L.get("name"): L for L in layers}
    problems = []
    if request["recipe"] == "text_overlay_v2":
        from aftereffects import schema_v2
        problems = schema_v2.verify_inspect(request["settings"], comp)
        if problems:
            raise AEError("VERIFY_FAILED", "; ".join(problems)[:1500], {"inspect": comp})
        return {"editable_layers": layers, "compositions": m.get("compositions"), "ae": m.get("ae"),
                "motion_blur": comp.get("motion_blur"), "shutter_angle": comp.get("shutter_angle")}
    for tid, text in expect_texts.items():
        L = by_name.get(tid)
        if not L:
            problems.append(f"text layer {tid!r} missing from the saved project")
        elif L.get("kind") != "text":
            problems.append(f"layer {tid!r} is {L.get('kind')} not text")
        elif (L.get("text") or "").replace("\r", "\n") != text:
            problems.append(f"layer {tid!r} text differs: {L.get('text')!r}")
    for sid in [s["id"] for s in request["settings"]["shapes"]]:
        if sid not in by_name:
            problems.append(f"shape layer {sid!r} missing")
    for L in layers:
        if L.get("kind") == "footage" and L.get("footage_missing"):
            problems.append(f"footage layer {L.get('name')!r} reports missing source")
    c = request["settings"]["composition"]
    for key in ("width", "height"):
        if comp.get(key) != c[key]:
            problems.append(f"saved comp {key} {comp.get(key)} != {c[key]}")
    if problems:
        raise AEError("VERIFY_FAILED", "; ".join(problems), {"inspect": comp})
    return {"editable_layers": layers, "compositions": m.get("compositions"), "ae": m.get("ae")}


def _proof_frames(ctx, request, master, out_dir, name):
    """Single PNG stills at the requested frames (v2 output_extras.proof_frames_f)."""
    frames = ((request["settings"].get("output_extras") or {}).get("proof_frames_f")) or []
    out = []
    for f in frames:
        dst = os.path.join(out_dir, f"{name}-proof-{int(f):05d}.png")
        media.extract_frame(master, int(f), dst, ctx.remaining(), ctx.cancel_check, ctx.log)
        out.append({"frame": int(f), "path": dst})
    return out


def _bundle(ctx, out_dir, name, project_path, staged, extra_files):
    ctx.phase("bundling")
    path = os.path.join(out_dir, f"{name}-bundle.zip")
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.write(project_path, os.path.basename(project_path))
        for aname, info in staged.items():
            z.write(info["path"], f"assets/{aname}{os.path.splitext(info['path'])[1]}")
        for arc, p in extra_files.items():
            z.write(p, arc)
    return path


def _provenance(ctx, request, staged, author_m, rendered_from, out):
    return {
        "engine": "aftereffects", "schema_version": schema.SCHEMA_VERSION,
        "recipe": request["recipe"], "recipe_revision": recipe_revision(request["recipe"]),
        "settings_sha256": hashlib.sha256(json.dumps(request["settings"], sort_keys=True).encode()).hexdigest(),
        "inputs": {n: {"sha256": i["sha256"], "size": i["size"], "kind": i["kind"],
                       **({"rasterized_from": i["rasterized_from"]} if i.get("rasterized_from") else {})}
                   for n, i in staged.items()},
        "host": ctx.host.info(), "ae": (author_m or {}).get("ae"),
        "ffmpeg": media.version(),
        "output_settings": {"om_template": ctx.host.om_template, "rs_template": ctx.host.rs_template,
                            "aerender_output": rendered_from,
                            "master": {"codec": "prores_ks", "profile": "4444", "pix_fmt": "yuva444p10le",
                                       "alpha": "straight"},
                            "review": {"codec": "libvpx-vp9", "pix_fmt": "yuva420p"}},
        "scope": {k: request.get(k) for k in ("org_id", "job_id", "order_id", "version")},
        "fonts": (author_m or {}).get("fonts"),
        "capabilities_sha256": _capabilities_sha(),
    }


def _capabilities_sha():
    try:
        from aftereffects import capabilities
        return capabilities.report()["capabilities_sha256"]
    except Exception:  # noqa: BLE001 - provenance only
        return None


def run(request, workspace, host, assets_local, log, cancel_check, timeout_s, progress=lambda f: None,
        phase=lambda p: None, name="overlay"):
    """Author + render + finish one validated request in `workspace`. Returns the result dict
    (paths, checks, timings, provenance) that is also written to workspace/out/manifest.json."""
    t_start = time.monotonic()
    ctx = _Ctx(workspace, host, log, cancel_check, time.monotonic() + timeout_s, progress, phase)
    for d in ("inputs", "project", "render", "out"):
        os.makedirs(os.path.join(workspace, d), exist_ok=True)
    out_dir = os.path.join(workspace, "out")
    manifest_out = os.path.join(out_dir, "manifest.json")
    result = {"ok": False, "workspace": workspace, "name": name}
    try:
        ctx.phase("validating")
        if request.get("recipe_revision") and request["recipe_revision"] != recipe_revision(request["recipe"]):
            raise AEError("RECIPE_REVISION_MISMATCH",
                          f"request pins recipe {request['recipe']}@{request['recipe_revision']}, this worker has "
                          f"{recipe_revision(request['recipe'])}")
        staged = _stage_assets(ctx, request, assets_local)
        ctx.phase("preflight")
        fonts_wanted = _preflight_fonts(request)

        ctx.phase("authoring")
        project_path = os.path.join(workspace, "project", "project.aep")
        job = {"manifest_path": os.path.join(workspace, "project", "author-manifest.json"),
               "project_path": project_path, "recipe": request["recipe"],
               "recipe_revision": recipe_revision(request["recipe"]), "composition": request["composition"],
               "settings": request["settings"], "assets": {n: i["path"] for n, i in staged.items()},
               "om_template": host.om_template}
        author_m = ctx.timed("author", lambda: _run_stage(ctx, "author", schema.RECIPES[request["recipe"]]["author"], job))
        if not os.path.exists(project_path):
            raise AEError("JSX_ERROR", "author script reported success but project.aep is missing")
        comp = request["settings"]["composition"]
        ac = author_m.get("comp") or {}
        if ac and (ac.get("width"), ac.get("height")) != (comp["width"], comp["height"]):
            raise AEError("VERIFY_FAILED", f"authored comp is {ac.get('width')}x{ac.get('height')}")

        ctx.phase("rendering")
        rendered, render_info = ctx.timed("render", lambda: host.render(
            project_path, request["composition"], os.path.join(workspace, "render"), comp["frames"],
            ctx.remaining(), cancel_check, ctx.progress, ctx.pid_sink))
        finished = _encode_and_verify(ctx, request, rendered, out_dir, name, render_info)
        inspected = _inspect(ctx, request, project_path, out_dir,
                             {t["id"]: t["text"] for t in schema.text_layers(request)})
        proofs = _proof_frames(ctx, request, finished["master"], out_dir, name)
        settings_copy = os.path.join(out_dir, "settings.json")
        with open(settings_copy, "w", encoding="utf-8") as f:
            json.dump(request, f, indent=1)
        recipe_copy = {f"recipes/{fn}": os.path.join(RECIPES_DIR, fn) for fn in recipe_files(request["recipe"])}
        bundle = _bundle(ctx, out_dir, name, project_path, staged, dict(recipe_copy, **{"settings.json": settings_copy}))
        ctx.timings["total_s"] = round(time.monotonic() - t_start, 3)
        result.update(ok=True, project=project_path, bundle=bundle, master=finished["master"], review=finished["review"],
                      contact_sheet=finished["contact_sheet"], checks=finished["checks"], review_info=finished["review_info"],
                      inspect=inspected, author=author_m, timings=ctx.timings, fonts=fonts_wanted, proofs=proofs,
                      easing_resolved=author_m.get("easing_resolved"), anchors_resolved=author_m.get("anchors_resolved"),
                      provenance=_provenance(ctx, request, staged, author_m, rendered, finished))
        ctx.progress(1.0)
    except AEError as e:
        result.update(error=e.to_dict(), timings=ctx.timings)
        raise
    except proc.Canceled:
        result.update(error={"code": "CANCELED", "message": "cancel requested"}, timings=ctx.timings)
        raise
    except proc.TimedOut as e:
        result.update(error={"code": "TIMEOUT", "message": str(e)}, timings=ctx.timings)
        raise
    finally:
        try:
            with open(manifest_out, "w", encoding="utf-8") as f:
                json.dump(result, f, indent=1, default=str)
        except OSError:
            pass
        result["manifest"] = manifest_out
    return result


def revise(request, changes, source_project, source_assets, workspace, host, log, cancel_check, timeout_s,
           progress=lambda f: None, phase=lambda p: None, name="overlay-v2"):
    """Open a delivered project, apply validated text/timing changes, save as a new
    project and render/verify it the same way. `source_assets` maps asset name ->
    staged path inside workspace/inputs (the bundle's assets, re-staged)."""
    t_start = time.monotonic()
    changes = schema.validate_changes(changes, request)
    ctx = _Ctx(workspace, host, log, cancel_check, time.monotonic() + timeout_s, progress, phase)
    for d in ("inputs", "project", "render", "out"):
        os.makedirs(os.path.join(workspace, d), exist_ok=True)
    out_dir = os.path.join(workspace, "out")
    result = {"ok": False, "workspace": workspace, "name": name, "changes": changes}
    try:
        ctx.phase("validating")
        staged = _stage_assets(ctx, request, source_assets)
        if not _inside(workspace, source_project):
            raise AEError("INVALID_REQUEST", "source project must be inside the attempt workspace")
        # The revised request: what the project holds after the changes.
        revised = json.loads(json.dumps(request))
        by_id = {}
        for group in ("texts", "shapes", "images"):
            for spec in revised["settings"][group]:
                by_id[spec["id"]] = spec
        for ch in changes:
            spec = by_id[ch["id"]]
            if "text" in ch:
                spec["text"] = ch["text"]
            if "in_s" in ch:
                spec["in_s"] = ch["in_s"]
            if "out_s" in ch:
                spec["out_s"] = ch["out_s"]
            if not spec["out_s"] > spec["in_s"]:
                raise AEError("INVALID_REQUEST", f"{ch['id']}: revised out_s must be after in_s")
        ctx.phase("authoring")
        project_path = os.path.join(workspace, "project", "project-revised.aep")
        job = {"manifest_path": os.path.join(workspace, "project", "revise-manifest.json"),
               "source_project_path": source_project, "project_path": project_path,
               "composition": request["composition"], "changes": changes}
        revise_m = ctx.timed("revise", lambda: _run_stage(ctx, "revise", schema.RECIPES[request["recipe"]]["revise"], job))
        comp = revised["settings"]["composition"]
        ctx.phase("rendering")
        rendered, render_info = ctx.timed("render", lambda: host.render(
            project_path, request["composition"], os.path.join(workspace, "render"), comp["frames"],
            ctx.remaining(), cancel_check, ctx.progress, ctx.pid_sink))
        finished = _encode_and_verify(ctx, revised, rendered, out_dir, name, render_info)
        inspected = _inspect(ctx, revised, project_path, out_dir, {t["id"]: t["text"] for t in revised["settings"]["texts"]})
        settings_copy = os.path.join(out_dir, "settings.json")
        with open(settings_copy, "w", encoding="utf-8") as f:
            json.dump(revised, f, indent=1)
        bundle = _bundle(ctx, out_dir, name, project_path, staged, {"settings.json": settings_copy})
        ctx.timings["total_s"] = round(time.monotonic() - t_start, 3)
        result.update(ok=True, project=project_path, bundle=bundle, master=finished["master"], review=finished["review"],
                      contact_sheet=finished["contact_sheet"], checks=finished["checks"], review_info=finished["review_info"],
                      inspect=inspected, revise=revise_m, timings=ctx.timings, revised_request=revised,
                      provenance=_provenance(ctx, revised, staged, revise_m, rendered, finished))
    except AEError as e:
        result.update(error=e.to_dict(), timings=ctx.timings)
        raise
    except proc.Canceled:
        result.update(error={"code": "CANCELED", "message": "cancel requested"}, timings=ctx.timings)
        raise
    except proc.TimedOut as e:
        result.update(error={"code": "TIMEOUT", "message": str(e)}, timings=ctx.timings)
        raise
    finally:
        manifest_out = os.path.join(out_dir, "manifest.json")
        try:
            with open(manifest_out, "w", encoding="utf-8") as f:
                json.dump(result, f, indent=1, default=str)
        except OSError:
            pass
        result["manifest"] = manifest_out
    return result


def clean_workspace(workspace):
    shutil.rmtree(workspace, ignore_errors=True)
