import React from 'react';
import {AbsoluteFill, Easing, Interactive, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {Audio, Video} from '@remotion/media';
import {BODY_FONT, DISPLAY_FONT, FontStyles} from './fonts';

const ACCENT = '#78E7D0';
const WHITE = '#F7F5F0';

const Footage: React.FC<{src: string; trimBefore: number; name: string; position?: string; dark?: number}> = ({src, trimBefore, name, position = '50% 50%', dark = .12}) => <AbsoluteFill style={{backgroundColor: '#05090B'}}><Video name={name} src={staticFile(src)} trimBefore={trimBefore} muted style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: position}} /><AbsoluteFill style={{background: `linear-gradient(180deg,rgba(2,5,6,.18),transparent 43%,rgba(2,5,6,${dark}) 100%)`}} /></AbsoluteFill>;

const ModelTitle: React.FC<{model: string; line: string; align?: 'left'|'center'; color?: string}> = ({model, line, align = 'center', color = ACCENT}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{justifyContent: 'flex-start', alignItems: align === 'center' ? 'center' : 'flex-start', padding: '130px 80px 0', textAlign: align, color: WHITE}}><Interactive.Div name={`${model} title`} style={{fontFamily: DISPLAY_FONT, fontSize: 112, lineHeight: .88, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', textShadow: '0 4px 32px rgba(0,0,0,.4)', opacity: interpolate(frame,[4,16],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}), translate: interpolate(frame,[4,16],['0px 32px','0px 0px'],{easing:Easing.bezier(.16,1,.3,1),extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}>{model}<div style={{fontFamily: BODY_FONT, fontSize: 25, lineHeight: 1.2, fontWeight: 400, letterSpacing: 5, color, marginTop: 22}}>{line}</div></Interactive.Div></AbsoluteFill>;
};

const Panel: React.FC<{children:React.ReactNode}> = ({children}) => <div style={{width:'100%',height:'33.333%',flexShrink:0,overflow:'hidden',position:'relative',borderBottom:'5px solid #05090B'}}>{children}<div style={{position:'absolute',left:0,right:0,bottom:0,height:22,background:'linear-gradient(transparent,rgba(0,0,0,.68))'}}/></div>;
const TriplePanel: React.FC<{top: React.ReactNode; middle: React.ReactNode; bottom: React.ReactNode}> = ({top,middle,bottom}) => <AbsoluteFill style={{backgroundColor:'#05090B'}}><Panel>{top}</Panel><Panel>{middle}</Panel><Panel>{bottom}</Panel></AbsoluteFill>;

const Intro: React.FC = () => <AbsoluteFill><Footage src="emas7/front-reveal.mp4" trimBefore={8} name="Opening e.MAS 7 detail" position="48% 50%" dark={.52} /><AbsoluteFill style={{alignItems:'center',paddingTop:140,textAlign:'center',color:WHITE}}><div style={{fontFamily:BODY_FONT,fontSize:26,letterSpacing:4}}>SINGAPORE · YOUR FIRST EV</div><div style={{fontFamily:DISPLAY_FONT,fontSize:106,lineHeight:.9,fontWeight:700,textTransform:'uppercase',marginTop:22}}>Two ways<br/>to start electric.</div></AbsoluteFill></AbsoluteFill>;

const FivePanels: React.FC = () => <TriplePanel top={<Footage src="emas5-video/freedom.mp4" trimBefore={2360} name="e.MAS 5 infotainment" position="50% 50%" />} middle={<Footage src="emas5-video/freedom.mp4" trimBefore={2840} name="e.MAS 5 rolling hero" position="50% 50%" />} bottom={<Footage src="emas5-video/freedom.mp4" trimBefore={1015} name="e.MAS 5 rear detail" position="50% 50%" />} />;
const SevenPanels: React.FC = () => <AbsoluteFill style={{backgroundColor:'#05090B',flexDirection:'row'}}><div style={{width:'33.333%',height:'100%',position:'relative',overflow:'hidden'}}><Footage src="emas7/cabin.mp4" trimBefore={6} name="e.MAS 7 cabin" position="52% 50%" /></div><div style={{width:'33.333%',height:'100%',position:'relative',overflow:'hidden',borderLeft:'5px solid #05090B',borderRight:'5px solid #05090B'}}><Footage src="emas7/side-profile.mp4" trimBefore={10} name="e.MAS 7 rolling hero" position="50% 50%" /></div><div style={{width:'33.333%',height:'100%',position:'relative',overflow:'hidden'}}><Footage src="emas7/details.mp4" trimBefore={4} name="e.MAS 7 light detail" position="50% 50%" /></div></AbsoluteFill>;

const Lifestyle: React.FC = () => <AbsoluteFill><Footage src="emas5-video/freedom.mp4" trimBefore={3135} name="e.MAS 5 city drive" position="50% 50%" dark={.45} /><AbsoluteFill style={{alignItems:'center',paddingTop:138,textAlign:'center',color:WHITE}}><div style={{fontFamily:DISPLAY_FONT,fontSize:78,lineHeight:.92,textTransform:'uppercase'}}>Modern tech.<br/>Everyday freedom.</div><div style={{fontFamily:BODY_FONT,fontSize:25,letterSpacing:3,marginTop:22,color:ACCENT}}>EFFORTLESS IN THE CITY</div></AbsoluteFill></AbsoluteFill>;

const SevenFeature: React.FC = () => <AbsoluteFill><Footage src="emas7/charging.mp4" trimBefore={5} name="e.MAS 7 charging" position="52% 50%" dark={.55} /><AbsoluteFill style={{alignItems:'center',paddingTop:132,textAlign:'center',color:WHITE}}><div style={{fontFamily:DISPLAY_FONT,fontSize:92,lineHeight:.9,textTransform:'uppercase'}}>More space.<br/>More possibility.</div><div style={{fontFamily:BODY_FONT,fontSize:25,letterSpacing:3,marginTop:22,color:ACCENT}}>COMFORT THAT GROWS WITH YOU</div></AbsoluteFill></AbsoluteFill>;

const Choice: React.FC = () => <AbsoluteFill style={{backgroundColor:'#05090B'}}><div style={{height:'50%',position:'relative',overflow:'hidden'}}><Footage src="emas5-video/freedom.mp4" trimBefore={1050} name="e.MAS 5 hero choice" position="50% 50%" /></div><div style={{height:'50%',position:'relative',overflow:'hidden',borderTop:'5px solid #05090B'}}><Footage src="emas7/front-reveal.mp4" trimBefore={18} name="e.MAS 7 hero choice" position="50% 55%" /></div><AbsoluteFill style={{justifyContent:'center',alignItems:'center',textAlign:'center',color:WHITE}}><div style={{fontFamily:BODY_FONT,fontSize:25,letterSpacing:5,color:ACCENT}}>YOUR FIRST EV?</div><div style={{fontFamily:DISPLAY_FONT,fontSize:92,lineHeight:.9,textTransform:'uppercase',marginTop:15,textShadow:'0 4px 35px rgba(0,0,0,.8)'}}>e.MAS 5<br/><span style={{fontFamily:BODY_FONT,fontSize:26,letterSpacing:4}}>OR</span><br/>e.MAS 7</div></AbsoluteFill></AbsoluteFill>;

const Cta: React.FC = () => <AbsoluteFill style={{backgroundColor:'black'}}><Video src={staticFile('cta/proton-logo.mp4')} muted style={{width:'100%',height:'100%',objectFit:'cover'}}/><AbsoluteFill style={{height:680,backgroundColor:'black',alignItems:'center',paddingTop:145,textAlign:'center',color:WHITE}}><div style={{fontFamily:BODY_FONT,fontSize:24,letterSpacing:4,color:ACCENT}}>MEET THE PROTON e.MAS</div><div style={{fontFamily:DISPLAY_FONT,fontSize:82,lineHeight:.92,textTransform:'uppercase',marginTop:22}}>Which one<br/>would you choose?</div><div style={{fontFamily:BODY_FONT,fontSize:27,letterSpacing:3,marginTop:28}}>e.MAS 5 · e.MAS 7</div></AbsoluteFill></AbsoluteFill>;

const Caption: React.FC<{text:string}> = ({text}) => <AbsoluteFill style={{justifyContent:'flex-end',alignItems:'center',padding:'0 90px 132px',pointerEvents:'none'}}><div style={{fontFamily:BODY_FONT,fontSize:34,lineHeight:1.18,color:'white',textAlign:'center',textShadow:'0 3px 16px rgba(0,0,0,.95)'}}>{text}</div></AbsoluteFill>;

export const FirstCarVideo: React.FC = () => <AbsoluteFill style={{backgroundColor:'#05090B'}}><FontStyles/><Sequence durationInFrames={105}><Intro/></Sequence><Sequence from={105} durationInFrames={90}><FivePanels/><ModelTitle model="e.MAS 5" line="COMPACT · URBAN · ELECTRIC"/></Sequence><Sequence from={195} durationInFrames={90}><SevenPanels/><ModelTitle model="e.MAS 7" line="SPACIOUS · REFINED · ELECTRIC"/></Sequence><Sequence from={285} durationInFrames={150}><Lifestyle/></Sequence><Sequence from={435} durationInFrames={150}><SevenFeature/></Sequence><Sequence from={585} durationInFrames={165}><Choice/></Sequence><Sequence from={750} durationInFrames={150}><Cta/></Sequence><Audio src={staticFile('audio/music.wav')} volume={.18}/><Audio src={staticFile('audio/voiceover/narration-v2.mp3')} volume={1}/><Sequence from={6} durationInFrames={96}><Caption text="Buying your first car? Start with something electric."/></Sequence><Sequence from={108} durationInFrames={87}><Caption text="The e.MAS 5 is compact, modern, and made for city life."/></Sequence><Sequence from={198} durationInFrames={87}><Caption text="The e.MAS 7 adds space, comfort, and versatility."/></Sequence><Sequence from={288} durationInFrames={144}><Caption text="Both bring smart technology and everyday EV ease."/></Sequence><Sequence from={438} durationInFrames={144}><Caption text="Choose the size that fits the life you're building."/></Sequence><Sequence from={594} durationInFrames={150}><Caption text="Compact and agile, or spacious enough to grow with you."/></Sequence><Sequence from={765} durationInFrames={120}><Caption text="Which Proton e.MAS would be your first car?"/></Sequence></AbsoluteFill>;
