import React from 'react';
import {AbsoluteFill, Easing, Interactive, interpolate, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {Audio, Video} from '@remotion/media';
import {BODY_FONT, DISPLAY_FONT, FontStyles} from './fonts';

const ACCENT = '#78E7D0';
const WHITE = '#F7F5F0';

const Footage: React.FC<{src: string; trimBefore: number; name: string; position?: string; dark?: number}> = ({src, trimBefore, name, position = '50% 50%', dark = .12}) => <AbsoluteFill style={{backgroundColor: '#05090B'}}><Video name={name} src={staticFile(src)} trimBefore={trimBefore} muted style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: position}} /><AbsoluteFill style={{background: `linear-gradient(180deg,rgba(2,5,6,.18),transparent 43%,rgba(2,5,6,${dark}) 100%)`}} /></AbsoluteFill>;

const PortraitAsLandscape: React.FC<{src: string; trimBefore: number; name: string; y?: number}> = ({src, trimBefore, name, y = -50}) => <AbsoluteFill style={{backgroundColor:'#05090B',overflow:'hidden'}}><Video name={name} src={staticFile(src)} trimBefore={trimBefore} muted style={{position:'absolute',width:'100%',height:'auto',left:0,top:'50%',translate:`0 ${y}%`}}/><AbsoluteFill style={{background:'linear-gradient(180deg,rgba(2,5,6,.14),transparent 46%,rgba(2,5,6,.16) 100%)'}}/></AbsoluteFill>;

const ModelTitle: React.FC<{model: string; line: string; align?: 'left'|'center'; color?: string}> = ({model, line, align = 'center', color = ACCENT}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{justifyContent: 'flex-start', alignItems: align === 'center' ? 'center' : 'flex-start', padding: '130px 80px 0', textAlign: align, color: WHITE}}><Interactive.Div name={`${model} title`} style={{fontFamily: DISPLAY_FONT, fontSize: 112, lineHeight: .88, fontWeight: 700, letterSpacing: 1, textTransform: 'uppercase', textShadow: '0 4px 32px rgba(0,0,0,.4)', opacity: interpolate(frame,[4,16],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}), translate: interpolate(frame,[4,16],['0px 32px','0px 0px'],{easing:Easing.bezier(.16,1,.3,1),extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}>{model}<div style={{fontFamily: BODY_FONT, fontSize: 25, lineHeight: 1.2, fontWeight: 400, letterSpacing: 5, color, marginTop: 22}}>{line}</div></Interactive.Div></AbsoluteFill>;
};

const Panel: React.FC<{children:React.ReactNode}> = ({children}) => <div style={{width:'100%',height:'33.333%',flexShrink:0,overflow:'hidden',position:'relative',borderBottom:'5px solid #05090B'}}>{children}<div style={{position:'absolute',left:0,right:0,bottom:0,height:22,background:'linear-gradient(transparent,rgba(0,0,0,.68))'}}/></div>;
const TriplePanel: React.FC<{top: React.ReactNode; middle: React.ReactNode; bottom: React.ReactNode}> = ({top,middle,bottom}) => <AbsoluteFill style={{backgroundColor:'#05090B'}}><Panel>{top}</Panel><Panel>{middle}</Panel><Panel>{bottom}</Panel></AbsoluteFill>;

const Intro: React.FC = () => <AbsoluteFill><Footage src="emas7/front-reveal.mp4" trimBefore={8} name="Opening e.MAS 7 detail" position="48% 50%" dark={.52} /><AbsoluteFill style={{alignItems:'center',paddingTop:140,textAlign:'center',color:WHITE}}><div style={{fontFamily:BODY_FONT,fontSize:26,letterSpacing:4}}>SINGAPORE · YOUR FIRST EV</div><div style={{fontFamily:DISPLAY_FONT,fontSize:106,lineHeight:.9,fontWeight:700,textTransform:'uppercase',marginTop:22}}>Two ways<br/>to start electric.</div></AbsoluteFill></AbsoluteFill>;

const FivePanels: React.FC = () => <TriplePanel top={<Footage src="emas5-video/freedom.mp4" trimBefore={2360} name="e.MAS 5 infotainment" position="50% 50%" />} middle={<Footage src="emas5-video/freedom.mp4" trimBefore={2840} name="e.MAS 5 rolling hero" position="50% 50%" />} bottom={<Footage src="emas5-video/freedom.mp4" trimBefore={1015} name="e.MAS 5 rear detail" position="50% 50%" />} />;
const SevenPanels: React.FC = () => <TriplePanel top={<PortraitAsLandscape src="emas7-requested/top-115-optimized.mp4" trimBefore={24} name="e.MAS 7 cockpit — requested top clip 115" y={-50} />} middle={<PortraitAsLandscape src="emas7-requested/center-25-optimized.mp4" trimBefore={24} name="e.MAS 7 front — requested centre clip 25" y={-50} />} bottom={<PortraitAsLandscape src="emas7-requested/bottom-24-optimized.mp4" trimBefore={24} name="e.MAS 7 cargo — requested bottom clip 24" y={-50} />} />;

const Lifestyle: React.FC = () => <AbsoluteFill><Footage src="emas5-video/freedom.mp4" trimBefore={3135} name="e.MAS 5 city drive" position="50% 50%" dark={.45} /><AbsoluteFill style={{alignItems:'center',paddingTop:138,textAlign:'center',color:WHITE}}><div style={{fontFamily:DISPLAY_FONT,fontSize:78,lineHeight:.92,textTransform:'uppercase'}}>Modern tech.<br/>Everyday freedom.</div><div style={{fontFamily:BODY_FONT,fontSize:25,letterSpacing:3,marginTop:22,color:ACCENT}}>EFFORTLESS IN THE CITY</div></AbsoluteFill></AbsoluteFill>;

const SevenFeature: React.FC = () => <AbsoluteFill style={{backgroundColor:'#05090B'}}><div style={{position:'absolute',left:0,right:0,top:610,height:700,overflow:'hidden'}}><PortraitAsLandscape src="emas7/charging.mp4" trimBefore={5} name="e.MAS 7 charging landscape feature" y={-50}/></div><AbsoluteFill style={{alignItems:'center',paddingTop:132,textAlign:'center',color:WHITE}}><div style={{fontFamily:DISPLAY_FONT,fontSize:92,lineHeight:.9,textTransform:'uppercase'}}>More space.<br/>More possibility.</div><div style={{fontFamily:BODY_FONT,fontSize:25,letterSpacing:3,marginTop:22,color:ACCENT}}>COMFORT THAT GROWS WITH YOU</div></AbsoluteFill></AbsoluteFill>;

const Choice: React.FC = () => <AbsoluteFill style={{backgroundColor:'#05090B'}}><div style={{height:'50%',position:'relative',overflow:'hidden'}}><Footage src="emas5-video/freedom.mp4" trimBefore={1050} name="e.MAS 5 hero choice" position="50% 50%" /></div><div style={{height:'50%',position:'relative',overflow:'hidden',borderTop:'5px solid #05090B'}}><Footage src="emas7-landscape/power-up.mp4" trimBefore={510} name="e.MAS 7 Singapore Flyer driving B-roll" position="50% 50%" dark={.24}/></div><AbsoluteFill style={{justifyContent:'center',alignItems:'center',textAlign:'center',color:WHITE}}><div style={{fontFamily:BODY_FONT,fontSize:25,letterSpacing:5,color:ACCENT}}>YOUR FIRST EV?</div><div style={{fontFamily:DISPLAY_FONT,fontSize:92,lineHeight:.9,textTransform:'uppercase',marginTop:15,textShadow:'0 4px 35px rgba(0,0,0,.8)'}}>e.MAS 5<br/><span style={{fontFamily:BODY_FONT,fontSize:26,letterSpacing:4}}>OR</span><br/>e.MAS 7</div></AbsoluteFill></AbsoluteFill>;

const Cta: React.FC = () => <AbsoluteFill style={{backgroundColor:'black'}}><Video src={staticFile('cta/proton-logo.mp4')} muted style={{width:'100%',height:'100%',objectFit:'cover'}}/><AbsoluteFill style={{height:680,backgroundColor:'black',alignItems:'center',paddingTop:145,textAlign:'center',color:WHITE}}><div style={{fontFamily:BODY_FONT,fontSize:24,letterSpacing:4,color:ACCENT}}>MEET THE PROTON e.MAS</div><div style={{fontFamily:DISPLAY_FONT,fontSize:82,lineHeight:.92,textTransform:'uppercase',marginTop:22}}>Which one<br/>would you choose?</div><div style={{fontFamily:BODY_FONT,fontSize:27,letterSpacing:3,marginTop:28}}>e.MAS 5 · e.MAS 7</div></AbsoluteFill></AbsoluteFill>;

const Caption: React.FC<{text:string}> = ({text}) => <AbsoluteFill style={{justifyContent:'flex-end',alignItems:'center',padding:'0 90px 132px',pointerEvents:'none'}}><div style={{fontFamily:BODY_FONT,fontSize:34,lineHeight:1.18,color:'white',textAlign:'center',textShadow:'0 3px 16px rgba(0,0,0,.95)'}}>{text}</div></AbsoluteFill>;

export const FirstCarVideo: React.FC = () => <AbsoluteFill style={{backgroundColor:'#05090B'}}><FontStyles/><Sequence durationInFrames={125}><Intro/></Sequence><Sequence from={125} durationInFrames={145}><FivePanels/><ModelTitle model="e.MAS 5" line="COMPACT · URBAN · ELECTRIC"/></Sequence><Sequence from={270} durationInFrames={120}><SevenPanels/><ModelTitle model="e.MAS 7" line="SPACIOUS · REFINED · ELECTRIC"/></Sequence><Sequence from={390} durationInFrames={120}><Lifestyle/></Sequence><Sequence from={510} durationInFrames={100}><SevenFeature/></Sequence><Sequence from={610} durationInFrames={150}><Choice/></Sequence><Sequence from={760} durationInFrames={140}><Cta/></Sequence><Audio src={staticFile('audio/music.wav')} volume={.15}/><Sequence from={6}><Audio src={staticFile('audio/voiceover-v3/intro.mp3')} volume={1}/></Sequence><Sequence from={128}><Audio src={staticFile('audio/voiceover-v3/emas5.mp3')} volume={1}/></Sequence><Sequence from={273}><Audio src={staticFile('audio/voiceover-v3/emas7.mp3')} volume={1}/></Sequence><Sequence from={393}><Audio src={staticFile('audio/voiceover-v3/emas5-city.mp3')} volume={1}/></Sequence><Sequence from={513}><Audio src={staticFile('audio/voiceover-v3/emas7-space.mp3')} volume={1}/></Sequence><Sequence from={613}><Audio src={staticFile('audio/voiceover-v3/choice.mp3')} volume={1}/></Sequence><Sequence from={775}><Audio src={staticFile('audio/voiceover-v3/cta.mp3')} volume={1}/></Sequence><Sequence from={6} durationInFrames={116}><Caption text="First car? Start electric."/></Sequence><Sequence from={128} durationInFrames={139}><Caption text="The e.MAS 5: compact, modern, city-ready."/></Sequence><Sequence from={273} durationInFrames={111}><Caption text="The e.MAS 7: extra space and comfort."/></Sequence><Sequence from={393} durationInFrames={116}><Caption text="The e.MAS 5 makes everyday city driving feel easy."/></Sequence><Sequence from={513} durationInFrames={92}><Caption text="The e.MAS 7 gives you room to grow."/></Sequence><Sequence from={613} durationInFrames={147}><Caption text="So, compact and agile—or spacious enough to grow with you?"/></Sequence><Sequence from={775} durationInFrames={108}><Caption text="Which Proton e.MAS would be your first car?"/></Sequence></AbsoluteFill>;
