"""video_gen runner: MiniMax H3 text / image / reference-to-video with native
audio, generated by the headless ComfyUI at config.COMFYUI_DIR, with an
optional SeedVR2 upscale pass (also usable on its own for any existing clip).

params (jsonb):
  video_gen:
    org_id / job_id      uuids, for scoping and logging only (farm_render_jobs
                         has no tenant column, so the platform scopes on these)
    mode                 t2v | i2v | r2v | upscale
                         (default t2v; i2v if a frame is given; r2v if refs given;
                          upscale if `source` is given)
    prompt               required for the generation modes; H3 refuses a request with no text
    duration_s           1-15, snapped UP to the 17k+5 frame grid at 24 fps (default 5)
    resolution           480p | 768p              (default 480p: this is a 16 GB card)
    ratio                16:9 | 9:16 | 1:1 | 4:3 | 3:4 | 21:9   (default 16:9)
    seed                 int (default 0)
    turbo                bool (default true) -> distilled LoRA, 8 steps fl2va / 4 steps ref2va
    steps                override; without turbo the default is 20
    shift_video / shift_audio   optional MiniMaxH3SigmaShift overrides (model defaults 12 / 3)
    first_frame / last_frame    {bucket, path}    (i2v)
    ref_images / ref_videos / ref_audios   [{bucket, path}]   (r2v; max 9 / 3 / 3)
    ref_image_size       match | max              (r2v; max is several times slower)
    source               {bucket, path}           (upscale mode: the clip to upscale)
    turntable            {front, rear: {bucket, path}, car, details, seconds_per_half (default 10),
                          resolution (default 768p), seed, fps (default 60), shorter_size (default 1080)}
                         mode "turntable": the anchored car 360 (studio/turntable.py): two 180-degree
                         image-to-video halves between the two photos, drift/cut checks with automatic
                         reseed/repair, seam-exact join, constant-speed remap, RIFE to fps. ~25-45 GPU
                         minutes at 768p; file it with timeout_minutes 120+. Sidecars: outputs/<jid>-piece1..N.mp4
                         (the 24 fps halves) and outputs/<jid>-joined24.mp4.
    upscale              optional resize pass, on generation modes (runs after the
                         clip is made) or the whole job in upscale mode:
                           method   lanczos (default: plain ffmpeg resize, instant, faithful)
                                    | seedvr2 (restoration model, ~55 s per second of video)
                           factor 2.0 | shorter_size px  (both methods)
                         seedvr2 only: color_correction wavelet|lab|adain|none (default wavelet),
                           temporal_overlap (latent frames, default 1), frames_per_chunk (4n+1,
                           default auto from free VRAM), seed, blend (0..1 share of SeedVR2 vs the
                           lanczos resize, default 0.5: raw SeedVR2 over-etches clean 768p H3
                           footage, see the chihuahua A/B), segment_frames (default 73: clips
                           longer than this are upscaled as consecutive segments and re-joined
                           with the source audio, because a whole-clip decode of 243 frames at
                           1664x960 took ComfyUI to 82 GB virtual on this 31 GB box and died)
                         When a generation job is upscaled, the base clip is also uploaded
                         as outputs/<jid>-base.mp4 (best effort, like matte's proof sheet).

WHY THIS ENGINE EXISTS: the platform's only source of generated b-roll is the
remote Seedance tool, which spends credits per clip. The 4080 on this box can
run H3 for free, slowly. It lives in the render farm rather than the agent
container for the same reason matte does: the container has no GPU.

VRAM: H3 at 16 GB streams weights from disk (--fast-disk) and needs the whole
card, so the TTS workers are paused for the duration (videogen/tts_guard) and
ComfyUI is told to drop its models afterwards (/free). A video job blocks the
single-instance render worker for minutes; use `priority` on the row.
"""
import os
import time

import db
import proc
from runners import gate_common
from videogen import comfy_client, graphs, segments, tts_guard
from studio import turntable as turntable_flow

_IMAGE_EXT = (".png", ".jpg", ".jpeg", ".webp")
_VIDEO_EXT = (".mp4", ".mov", ".webm", ".mkv")
_AUDIO_EXT = (".wav", ".mp3", ".flac", ".ogg", ".m4a")


def _fetch(ref, work_dir, name, log, allowed):
    if not isinstance(ref, dict) or not ref.get("bucket") or not ref.get("path"):
        raise RuntimeError(f"video_gen input {name} must be {{bucket, path}}, got {ref!r}")
    local = gate_common.download(ref["bucket"], ref["path"], work_dir, name, log)
    if not local.lower().endswith(allowed):
        raise RuntimeError(f"video_gen input {name}: unsupported type {os.path.splitext(local)[1]!r}")
    return local


def _run_prompt(jid, graph, label, heartbeat, cancel_check, deadline, dest, log):
    """Submit one graph, wait for it, fetch its video to dest. Raises on cancel/timeout."""
    db.set_phase(jid, f"{label}: queued", int(heartbeat.progress))
    prompt_id = comfy_client.submit(graph)
    log(f"comfyui prompt {prompt_id} ({label})")

    def on_status(phase, _progress):
        db.set_phase(jid, f"{label}: {phase}"[:60])

    remaining = max(30, int(deadline - time.monotonic()))
    try:
        outputs = comfy_client.wait(prompt_id, on_status, cancel_check, remaining)
    except comfy_client._CanceledSignal:
        raise proc.Canceled()
    db.set_phase(jid, f"{label}: fetching")
    comfy_client.fetch_output(outputs, dest)
    if not os.path.exists(dest) or os.path.getsize(dest) == 0:
        raise RuntimeError(f"comfyui reported success for {label} but no video was retrieved")
    log(f"{label} done: {os.path.getsize(dest)} bytes")
    return dest


def _upscale_clip(jid, src_local, u, work_dir, heartbeat, cancel_check, deadline, dest, log):
    """Resize pass over src_local: plain lanczos (default) or SeedVR2 in segments."""
    method = (u.get("method") or "lanczos").lower()
    if method not in ("lanczos", "seedvr2"):
        raise RuntimeError(f"upscale.method must be lanczos or seedvr2, got {method!r}")
    if method == "lanczos":
        db.set_phase(jid, "upscale: lanczos")
        return segments.lanczos(src_local, dest, factor=u.get("factor"), shorter_size=u.get("shorter_size"), log=log)
    seg_frames = int(u.get("segment_frames") or segments.DEFAULT_SEGMENT_FRAMES)
    seg_dir = os.path.join(work_dir, "segments")
    os.makedirs(seg_dir, exist_ok=True)
    parts, fps, total = segments.split(src_local, seg_frames, seg_dir, log)
    if len(parts) == 1:
        name = comfy_client.upload_input(src_local)
        graph, meta = graphs.build_upscale(name, u, f"video_gen/{jid}-upscaled")
        log(f"upscale {meta} ({total} frames)")
        return _run_prompt(jid, graph, "upscale", heartbeat, cancel_check, deadline, dest, log)
    done = []
    p0 = heartbeat.progress
    for i, part in enumerate(parts):
        name = comfy_client.upload_input(part)
        graph, meta = graphs.build_upscale(name, u, f"video_gen/{jid}-seg{i:03d}")
        if i == 0:
            log(f"upscale {meta} ({total} frames in {len(parts)} segments of {seg_frames})")
        out = os.path.join(seg_dir, f"up_{i:03d}.mp4")
        _run_prompt(jid, graph, f"upscale {i + 1}/{len(parts)}", heartbeat, cancel_check, deadline, out, log)
        done.append(out)
        heartbeat.progress = int(p0 + (90 - p0) * (i + 1) / len(parts))
        # Drop the decoded frames of this segment before the next one is loaded.
        comfy_client.free()
    db.set_phase(jid, "upscale: joining segments")
    return segments.concat(done, src_local, dest, log)


class _TurntableApi:
    """studio/turntable.py's api, backed directly by ComfyUI (no nested farm jobs:
    the worker is single-instance, so a job that queued sub-jobs would wait forever)."""

    def __init__(self, jid, work_dir, heartbeat, cancel_check, deadline, log):
        self.jid, self.heartbeat, self.cancel_check, self.deadline, self.log = jid, heartbeat, cancel_check, deadline, log
        self.work_dir = os.path.join(work_dir, "turntable")
        os.makedirs(self.work_dir, exist_ok=True)
        self._n, self._results = 0, {}

    def phase(self, text, progress=None):
        if progress is not None:
            self.heartbeat.progress = progress
        db.set_phase(self.jid, text[:60], progress)

    def check_cancel(self):
        if self.cancel_check():
            raise proc.Canceled()

    def upload(self, local):
        return {"name": comfy_client.upload_input(local)}

    def submit(self, vg, label):
        self._n += 1
        key = f"{self._n:02d}"
        names = {"first_frame": vg["first_frame"]["name"], "last_frame": vg["last_frame"]["name"]}
        graph, meta = graphs.build("i2v", vg, names, f"video_gen/{self.jid}-tt{key}")
        self.log(f"turntable {label}: {meta['width']}x{meta['height']} {meta['length']}f seed={meta['seed']}")
        dest = os.path.join(self.work_dir, f"tt{key}.mp4")
        self._results[key] = _run_prompt(self.jid, graph, f"turntable {label}"[:40], self.heartbeat, self.cancel_check,
                                         self.deadline, dest, self.log)
        return key

    def wait(self, key, label):
        return self._results[key]


def run(job, repo, work_dir, heartbeat, log, cancel_check, timeout_seconds):
    jid = job["id"]
    p = (job.get("params") or {}).get("video_gen") or {}
    deadline = time.monotonic() + timeout_seconds

    mode = p.get("mode")
    if not mode:
        if p.get("turntable"):
            mode = "turntable"
        elif p.get("source"):
            mode = "upscale"
        elif p.get("first_frame") or p.get("last_frame"):
            mode = "i2v"
        elif p.get("ref_images") or p.get("ref_videos") or p.get("ref_audios"):
            mode = "r2v"
        else:
            mode = "t2v"
    if mode not in graphs.MODES:
        raise RuntimeError(f"video_gen mode must be one of {graphs.MODES}, got {mode!r}")
    if mode in graphs.GEN_MODES and not (p.get("prompt") or "").strip():
        raise RuntimeError("video_gen needs params.video_gen.prompt")
    upscale = p.get("upscale")
    tt = p.get("turntable") or {}
    if mode == "turntable":
        for k in ("front", "rear", "car"):
            if not tt.get(k):
                raise RuntimeError(f"turntable mode needs params.video_gen.turntable.{k}")
    if mode == "upscale":
        upscale = upscale or {}
        if not p.get("source"):
            raise RuntimeError("upscale mode needs params.video_gen.source {bucket, path}")

    # 1. Inputs: bucket objects -> local
    db.set_phase(jid, "downloading inputs", 1)
    inputs = {}
    if mode == "i2v":
        for key in ("first_frame", "last_frame"):
            if p.get(key):
                inputs[key] = _fetch(p[key], work_dir, key, log, _IMAGE_EXT)
    elif mode == "r2v":
        for key, allowed, cap in (("ref_images", _IMAGE_EXT, graphs.MAX_REF_IMAGES),
                                  ("ref_videos", _VIDEO_EXT, graphs.MAX_REF_VIDEOS),
                                  ("ref_audios", _AUDIO_EXT, graphs.MAX_REF_AUDIOS)):
            refs = list(p.get(key) or [])
            if len(refs) > cap:
                raise RuntimeError(f"video_gen: at most {cap} {key} (got {len(refs)})")
            inputs[key] = [_fetch(r, work_dir, f"{key}_{i}", log, allowed) for i, r in enumerate(refs)]
    elif mode == "upscale":
        inputs["source"] = _fetch(p["source"], work_dir, "source", log, _VIDEO_EXT)
    elif mode == "turntable":
        for key in ("front", "rear"):
            inputs[key] = _fetch(tt[key], work_dir, key, log, _IMAGE_EXT)
    heartbeat.progress = 3

    if mode == "upscale" and (upscale.get("method") or "lanczos").lower() == "lanczos":
        # Pure ffmpeg: no ComfyUI, no TTS pause, no GPU.
        out_local = _upscale_clip(jid, inputs["source"], upscale, work_dir, heartbeat, cancel_check,
                                  deadline, os.path.join(work_dir, "video_gen-upscaled.mp4"), log)
        heartbeat.progress = 95
        return out_local, "mp4", "video/mp4"

    # 2. Server up (lazy start), TTS workers out of the way
    db.set_phase(jid, "starting comfyui", 3)
    comfy_client.ensure_server(log)
    with tts_guard.paused(log):
        try:
            stats = comfy_client.system_stats()
            dev = (stats.get("devices") or [{}])[0]
            log(f"comfyui {stats.get('system', {}).get('comfyui_version')} on {dev.get('name')} "
                f"vram_free={dev.get('vram_free', 0) // (1 << 20)} MiB")
        except Exception as e:  # noqa: BLE001 - telemetry only
            log(f"system_stats unavailable: {e}")

        db.set_phase(jid, "uploading inputs", 5)
        names = {}
        for key, val in inputs.items():
            if key in ("source", "front", "rear"):
                continue  # source: uploaded per segment by _upscale_clip; front/rear: padded first by the turntable flow
            if isinstance(val, list):
                names[key] = [comfy_client.upload_input(v) for v in val]
            else:
                names[key] = comfy_client.upload_input(val)

        try:
            if mode in graphs.GEN_MODES:
                graph, meta = graphs.build(mode, p, names, f"video_gen/{jid}")
                log(f"video_gen {mode} {meta['width']}x{meta['height']} {meta['length']}f (~{meta['seconds']}s) "
                    f"steps={meta['steps']} turbo={meta['turbo']} seed={meta['seed']} family={meta['family']}")
                heartbeat.progress = 8
                base_local = _run_prompt(jid, graph, "generate", heartbeat, cancel_check, deadline,
                                         os.path.join(work_dir, "video_gen.mp4"), log)
                out_local = base_local
                if upscale:
                    # Free H3 before SeedVR2 so the two never share the 16 GB.
                    comfy_client.free()
                    heartbeat.progress = 55
                    # The base clip goes up BEFORE the upscale is attempted, matte-proof-sheet
                    # style: if SeedVR2 fails the job fails, but the generated video is not
                    # lost and the platform can still fetch outputs/<jid>-base.mp4.
                    db.set_phase(jid, "uploading base clip", 55)
                    try:
                        remote = db.upload_file(f"outputs/{jid}-base.mp4", base_local, "video/mp4")
                        log(f"base clip -> {remote}")
                    except Exception as exc:  # noqa: BLE001
                        log(f"base clip upload failed (continuing to upscale): {exc}")
                    db.set_phase(jid, "upscale: preparing", 56)
                    out_local = _upscale_clip(jid, base_local, upscale, work_dir, heartbeat, cancel_check,
                                              deadline, os.path.join(work_dir, "video_gen-upscaled.mp4"), log)
            elif mode == "turntable":
                opts = {"front_local": inputs["front"], "rear_local": inputs["rear"], "car": tt["car"],
                        "details": tt.get("details", "")}
                for k in ("resolution", "ratio", "seconds_per_half", "seed", "fps", "shorter_size", "density"):
                    if tt.get(k) not in (None, ""):
                        opts[k] = tt[k]
                api = _TurntableApi(jid, work_dir, heartbeat, cancel_check, deadline, log)
                heartbeat.progress = 5
                res = turntable_flow.run(opts, api, log)
                # Sidecars, matte-proof-sheet style: the 24 fps pieces and the join, best effort.
                sidecars = [(f"piece{i + 1}", pth) for i, pth in enumerate(res["pieces"])] + [("joined24", res["joined"])]
                for name, pth in sidecars:
                    try:
                        db.upload_file(f"outputs/{jid}-{name}.mp4", pth, "video/mp4")
                    except Exception as exc:  # noqa: BLE001
                        log(f"sidecar {name} upload failed: {exc}")
                log(f"turntable done: {res['frames']} frames at {res['fps']} fps, {len(res['pieces'])} pieces")
                out_local = res["video"]
            else:
                heartbeat.progress = 8
                out_local = _upscale_clip(jid, inputs["source"], upscale, work_dir, heartbeat, cancel_check,
                                          deadline, os.path.join(work_dir, "video_gen-upscaled.mp4"), log)
        finally:
            # Hand the card back whether we succeeded, failed or were canceled.
            comfy_client.free()

    heartbeat.progress = 95
    # run_job uploads to outputs/<jid>.mp4 and writes output_path / signed_url
    # on the row, exactly like every other engine.
    return out_local, "mp4", "video/mp4"
