"""video_gen runner: MiniMax H3 text / image / reference-to-video with native
audio, generated by the headless ComfyUI at config.COMFYUI_DIR, with an
optional SeedVR2 upscale pass (also usable on its own for any existing clip).

params (jsonb):
  video_gen:
    org_id / job_id      uuids, for scoping and logging only (farm_render_jobs
                         has no tenant column, so the platform scopes on these)
    mode                 t2v | i2v | r2v | upscale
                         (default t2v; i2v if a frame is given; r2v if refs given;
                          upscale if `source` is given)
    prompt               required for the generation modes; H3 refuses a request with no text
    duration_s           1-15, snapped UP to the 17k+5 frame grid at 24 fps (default 5)
    resolution           480p | 768p              (default 480p: this is a 16 GB card)
    ratio                16:9 | 9:16 | 1:1 | 4:3 | 3:4 | 21:9   (default 16:9)
    seed                 int (default 0)
    turbo                bool (default true) -> distilled LoRA, 8 steps fl2va / 4 steps ref2va
    steps                override; without turbo the default is 20
    shift_video / shift_audio   optional MiniMaxH3SigmaShift overrides (model defaults 12 / 3)
    first_frame / last_frame    {bucket, path}    (i2v)
    ref_images / ref_videos / ref_audios   [{bucket, path}]   (r2v; max 9 / 3 / 3)
    ref_image_size       match | max              (r2v; max is several times slower)
    source               {bucket, path}           (upscale mode: the clip to upscale)
    turntable            mode "turntable": the anchored car 360 (studio/turntable.py).
                           front, rear          {bucket, path} straight-on photos (two-anchor: 2 x 180 degrees)
                           left, right          {bucket, path} the VEHICLE's left/right sides; giving both
                                                switches to four-anchor mode (4 x 90 degrees:
                                                front_to_left, left_to_rear, rear_to_right, right_to_front,
                                                clockwise seen from above). One side alone is rejected.
                           car, details         one line about the car; things to hold (badge, exact plate text)
                           seconds_per_half     default 10 (two-anchor); seconds_per_quarter default 5 (four-anchor)
                           segments             optional consecutive subset of the sequence to make, e.g.
                                                ["front_to_left"] for a reviewable quarter; omit for the full turn
                           ready_segments       {name: {bucket, path}} native 24 fps segment clips to reuse
                                                instead of regenerating (a previous job's outputs/<id>-<name>.mp4
                                                or a platform asset); mix with generated ones freely
                           resolution (768p), seed, fps (60), shorter_size (1080)
                         Each segment is one image-to-video generation between its two anchor photos, drift
                         and cut checked with automatic reseed/repair inside the segment, then the requested
                         segments are joined on their shared frames, checked at every seam, remapped to
                         constant speed and RIFE'd to fps. Only a complete sequence loops. Sidecars:
                         outputs/<jid>-<segment>.mp4 (native 24 fps, one per segment), outputs/<jid>-joined24.mp4,
                         outputs/<jid>-manifest.json (segments, seams, defects, timing); two-anchor jobs also
                         keep outputs/<jid>-piece1..2.mp4 as before. ~9 min per 10 s half, ~5 min per 5 s
                         quarter at 768p, plus retries; file with timeout_minutes 150 (two) / 180 (four).
    upscale              optional resize pass, on generation modes (runs after the
                         clip is made) or the whole job in upscale mode:
                           method   lanczos (default: plain ffmpeg resize, instant, faithful)
                                    | seedvr2 (restoration model, ~55 s per second of video)
                           factor 2.0 | shorter_size px  (both methods)
                         seedvr2 only: color_correction wavelet|lab|adain|none (default wavelet),
                           temporal_overlap (latent frames, default 1), frames_per_chunk (4n+1,
                           default auto from free VRAM), seed, blend (0..1 share of SeedVR2 vs the
                           lanczos resize, default 0.5: raw SeedVR2 over-etches clean 768p H3
                           footage, see the chihuahua A/B), segment_frames (default 73: clips
                           longer than this are upscaled as consecutive segments and re-joined
                           with the source audio, because a whole-clip decode of 243 frames at
                           1664x960 took ComfyUI to 82 GB virtual on this 31 GB box and died)
                         When a generation job is upscaled, the base clip is also uploaded
                         as outputs/<jid>-base.mp4 (best effort, like matte's proof sheet).

WHY THIS ENGINE EXISTS: the platform's only source of generated b-roll is the
remote Seedance tool, which spends credits per clip. The 4080 on this box can
run H3 for free, slowly. It lives in the render farm rather than the agent
container for the same reason matte does: the container has no GPU.

VRAM: H3 at 16 GB streams weights from disk (--fast-disk) and needs the whole
card, so the TTS workers are paused for the duration (videogen/tts_guard) and
ComfyUI is told to drop its models afterwards (/free). A video job blocks the
single-instance render worker for minutes; use `priority` on the row.
"""
import os
import time
from datetime import datetime

import config
import db
import proc
from runners import gate_common
import json

from videogen import comfy_client, estimate, graphs, media_type, segments, tts_guard
from studio import turntable as turntable_flow

_IMAGE, _VIDEO, _AUDIO = ("image",), ("video",), ("audio",)


def _fetch(ref, work_dir, name, log, allowed, download=None):
    """Download one {bucket, path} input and return a local path whose suffix matches
    its content. Platform assets are content-addressed (assets/sha256/<hex>, no
    extension), so the type comes from the bytes, verified with ffprobe; a file
    that is neither a decodable image/video/audio of the expected kind is rejected."""
    if not isinstance(ref, dict) or not ref.get("bucket") or not ref.get("path"):
        raise RuntimeError(f"video_gen input {name} must be {{bucket, path}}, got {ref!r}")
    local = (download or gate_common.download)(ref["bucket"], ref["path"], work_dir, name, log)
    return media_type.ensure_extension(local, allowed, name=name)


def _run_prompt(jid, graph, label, heartbeat, cancel_check, deadline, dest, log, prange=None, hint=None,
                after_seconds=0.0, after_text=""):
    """Submit one graph, wait for it, fetch its video to dest. Raises on cancel/timeout.

    prange         (lo, hi) job-progress percent this prompt spans (default: from the current
                   heartbeat progress to 90)
    hint           videogen.estimate.sampling_hint(...) for the ETA before the first step
    after_seconds  work that still follows this prompt inside the job (for the "job ~N min" text)
    after_text     e.g. " - then half 2 + join" appended to the phase
    """
    lo, hi = prange or (int(heartbeat.progress), 90)

    def on_status(phase, frac, eta):
        heartbeat.progress = int(lo + (hi - lo) * max(0.0, min(1.0, frac)))
        left = eta + after_seconds
        text = f"{label}: {phase} - ~{estimate.fmt_eta(eta)} left"
        if after_seconds:
            text += f" - job ~{estimate.fmt_eta(left)}{after_text}"
        db.set_phase(jid, text[:120], heartbeat.progress)

    outputs = None
    for attempt in (1, 2):
        since = datetime.now().isoformat()
        db.set_phase(jid, f"{label}: queued" + (" (retry)" if attempt > 1 else ""), lo)
        prompt_id = comfy_client.submit(graph)
        log(f"comfyui prompt {prompt_id} ({label})" + (" retry" if attempt > 1 else ""))
        remaining = max(30, int(deadline - time.monotonic()))
        try:
            outputs = comfy_client.wait(prompt_id, on_status, cancel_check, remaining, hint=hint, since_iso=since)
            break
        except comfy_client._CanceledSignal:
            raise proc.Canceled()
        except comfy_client.ComfyError as exc:
            # --fast-disk streams the checkpoint from disk; twice today a read failed the moment a
            # freshly /free'd model was re-staged ("HostBuffer.read_file_slice failed",
            # "hostbuf_file_reader_read failed"). A retry after a /free has always succeeded.
            if attempt == 1 and "hostbuf" in str(exc).lower():
                log(f"{label}: transient weight-stream read error, retrying once: {exc}")
                comfy_client.free()
                time.sleep(5)
                continue
            raise
    db.set_phase(jid, f"{label}: fetching")
    comfy_client.fetch_output(outputs, dest)
    if not os.path.exists(dest) or os.path.getsize(dest) == 0:
        raise RuntimeError(f"comfyui reported success for {label} but no video was retrieved")
    log(f"{label} done: {os.path.getsize(dest)} bytes")
    return dest


def _upscale_clip(jid, src_local, u, work_dir, heartbeat, cancel_check, deadline, dest, log):
    """Resize pass over src_local: plain lanczos (default) or SeedVR2 in segments."""
    method = (u.get("method") or "lanczos").lower()
    if method not in ("lanczos", "seedvr2"):
        raise RuntimeError(f"upscale.method must be lanczos or seedvr2, got {method!r}")
    if method == "lanczos":
        db.set_phase(jid, "upscale: lanczos")
        return segments.lanczos(src_local, dest, factor=u.get("factor"), shorter_size=u.get("shorter_size"), log=log)
    seg_frames = int(u.get("segment_frames") or segments.DEFAULT_SEGMENT_FRAMES)
    seg_dir = os.path.join(work_dir, "segments")
    os.makedirs(seg_dir, exist_ok=True)
    parts, fps, total = segments.split(src_local, seg_frames, seg_dir, log)
    if len(parts) == 1:
        name = comfy_client.upload_input(src_local)
        graph, meta = graphs.build_upscale(name, u, f"video_gen/{jid}-upscaled")
        log(f"upscale {meta} ({total} frames)")
        return _run_prompt(jid, graph, "upscale", heartbeat, cancel_check, deadline, dest, log)
    done = []
    p0 = heartbeat.progress
    for i, part in enumerate(parts):
        name = comfy_client.upload_input(part)
        graph, meta = graphs.build_upscale(name, u, f"video_gen/{jid}-seg{i:03d}")
        if i == 0:
            log(f"upscale {meta} ({total} frames in {len(parts)} segments of {seg_frames})")
        out = os.path.join(seg_dir, f"up_{i:03d}.mp4")
        _run_prompt(jid, graph, f"upscale {i + 1}/{len(parts)}", heartbeat, cancel_check, deadline, out, log)
        done.append(out)
        heartbeat.progress = int(p0 + (90 - p0) * (i + 1) / len(parts))
        # Drop the decoded frames of this segment before the next one is loaded.
        comfy_client.free()
    db.set_phase(jid, "upscale: joining segments")
    return segments.concat(done, src_local, dest, log)


def turntable_manifest(jid, res):
    """The storage contract for a turntable job's pieces: which native 24 fps segment lives where,
    how the seams measured, and what still looks wrong. outputs/<jid>-manifest.json."""
    segs = {}
    for name in res["order"]:
        s = res["segments"][name]
        segs[name] = {"bucket": config.BUCKET, "path": f"outputs/{jid}-{name}.mp4", "frames": s["frames"],
                      "seconds": s["seconds"], "fps": graphs.FPS, "reused": s["reused"], "attempts": s["attempts"],
                      "repairs": s["repairs"]}
    return {"job_id": jid, "variant": f"{res['variant']}_anchor", "sequence": turntable_flow.SEQUENCES[res["variant"]],
            "segments_in_order": res["order"], "complete": res["complete"], "loops": res["loops"],
            "canvas": {"width": res["canvas"][0], "height": res["canvas"][1], "fps": graphs.FPS},
            "output": {"bucket": config.BUCKET, "path": f"outputs/{jid}.mp4", "width": res["width"],
                       "height": res["height"], "fps": res["fps"], "frames": res["frames"],
                       "note": "RIFE-interpolated and lanczos-resized master; detail is that of the canvas"},
            "joined_native": {"bucket": config.BUCKET, "path": f"outputs/{jid}-joined24.mp4"},
            "segments": segs, "seams": res["seams"], "defects": res["defects"], "timing_s": res["timing"],
            "plateau_motion": round(res["plateau"], 2)}


def _upload_turntable_sidecars(jid, res, log):
    """Best effort, matte-proof-sheet style: every native-rate segment, the native join, the manifest,
    and (two-anchor only) the legacy piece1..N names."""
    db.set_phase(jid, "uploading", 95)
    files = [(f"{name}.mp4", res["segments"][name]["local"], "video/mp4") for name in res["order"]]
    files.append(("joined24.mp4", res["joined"], "video/mp4"))
    if res["variant"] == "two":
        files += [(f"piece{i + 1}.mp4", res["segments"][name]["local"], "video/mp4") for i, name in enumerate(res["order"])]
    for name, pth, ctype in files:
        try:
            db.upload_file(f"outputs/{jid}-{name}", pth, ctype)
        except Exception as exc:  # noqa: BLE001
            log(f"sidecar {name} upload failed: {exc}")
    man = os.path.join(os.path.dirname(res["joined"]), "manifest.json")
    with open(man, "w", encoding="utf-8") as f:
        json.dump(turntable_manifest(jid, res), f, indent=1)
    try:
        db.upload_file(f"outputs/{jid}-manifest.json", man, "application/json")
    except Exception as exc:  # noqa: BLE001
        log(f"manifest upload failed: {exc}")


class _TurntableApi:
    """studio/turntable.py's api, backed directly by ComfyUI (no nested farm jobs:
    the worker is single-instance, so a job that queued sub-jobs would wait forever)."""

    def __init__(self, jid, work_dir, heartbeat, cancel_check, deadline, log):
        self.jid, self.heartbeat, self.cancel_check, self.deadline, self.log = jid, heartbeat, cancel_check, deadline, log
        self.work_dir = os.path.join(work_dir, "turntable")
        os.makedirs(self.work_dir, exist_ok=True)
        self._n, self._results = 0, {}
        self.halves_done = 0   # the flow tells us via phase() text; we count finished generations

    def phase(self, text, progress=None):
        if progress is not None:
            self.heartbeat.progress = progress
        db.set_phase(self.jid, text[:120], progress)

    def check_cancel(self):
        if self.cancel_check():
            raise proc.Canceled()

    def upload(self, local):
        return {"name": comfy_client.upload_input(local)}

    def submit(self, vg, label, prange=None, after_seconds=0.0, after_text=""):
        """Run one anchored i2v generation synchronously. prange is the job-progress span the
        flow planned for this segment; retries and repairs re-enter the same span, so the
        low end is clamped to the current progress to keep the bar monotonic."""
        self._n += 1
        key = f"{self._n:02d}"
        names = {"first_frame": vg["first_frame"]["name"], "last_frame": vg["last_frame"]["name"]}
        graph, meta = graphs.build("i2v", vg, names, f"video_gen/{self.jid}-tt{key}")
        self.log(f"{label}: {meta['width']}x{meta['height']} {meta['length']}f seed={meta['seed']}")
        dest = os.path.join(self.work_dir, f"tt{key}.mp4")
        lo, hi = prange or (5, 85)
        lo = max(lo, int(self.heartbeat.progress))
        hi = max(hi, lo + 1)
        self._results[key] = _run_prompt(self.jid, graph, label[:60], self.heartbeat, self.cancel_check,
                                         self.deadline, dest, self.log, prange=(lo, hi),
                                         hint=estimate.sampling_hint(vg, "i2v"), after_seconds=after_seconds,
                                         after_text=after_text)
        return key

    def wait(self, key, label):
        return self._results[key]


def run(job, repo, work_dir, heartbeat, log, cancel_check, timeout_seconds):
    jid = job["id"]
    p = (job.get("params") or {}).get("video_gen") or {}
    deadline = time.monotonic() + timeout_seconds

    mode = p.get("mode")
    if not mode:
        if p.get("turntable"):
            mode = "turntable"
        elif p.get("source"):
            mode = "upscale"
        elif p.get("first_frame") or p.get("last_frame"):
            mode = "i2v"
        elif p.get("ref_images") or p.get("ref_videos") or p.get("ref_audios"):
            mode = "r2v"
        else:
            mode = "t2v"
    if mode not in graphs.MODES:
        raise RuntimeError(f"video_gen mode must be one of {graphs.MODES}, got {mode!r}")
    if mode in graphs.GEN_MODES and not (p.get("prompt") or "").strip():
        raise RuntimeError("video_gen needs params.video_gen.prompt")
    upscale = p.get("upscale")
    tt = p.get("turntable") or {}
    tt_plan = None
    if mode == "turntable":
        try:
            tt_plan = turntable_flow.plan(tt)
        except ValueError as exc:
            raise RuntimeError(f"turntable: {exc}")
        log(f"turntable {tt_plan['variant']}-anchor: generate {tt_plan['generate']}, reuse {tt_plan['reuse']}, "
            f"{'complete loop' if tt_plan['complete'] else 'partial: ' + ', '.join(tt_plan['requested'])}")
    if mode == "upscale":
        upscale = upscale or {}
        if not p.get("source"):
            raise RuntimeError("upscale mode needs params.video_gen.source {bucket, path}")

    # 1. Inputs: bucket objects -> local
    db.set_phase(jid, "downloading inputs", 1)
    inputs = {}
    if mode == "i2v":
        for key in ("first_frame", "last_frame"):
            if p.get(key):
                inputs[key] = _fetch(p[key], work_dir, key, log, _IMAGE)
    elif mode == "r2v":
        for key, allowed, cap in (("ref_images", _IMAGE, graphs.MAX_REF_IMAGES),
                                  ("ref_videos", _VIDEO, graphs.MAX_REF_VIDEOS),
                                  ("ref_audios", _AUDIO, graphs.MAX_REF_AUDIOS)):
            refs = list(p.get(key) or [])
            if len(refs) > cap:
                raise RuntimeError(f"video_gen: at most {cap} {key} (got {len(refs)})")
            inputs[key] = [_fetch(r, work_dir, f"{key}_{i}", log, allowed) for i, r in enumerate(refs)]
    elif mode == "upscale":
        inputs["source"] = _fetch(p["source"], work_dir, "source", log, _VIDEO)
    elif mode == "turntable":
        inputs["anchors"] = {a: _fetch(tt[a], work_dir, a, log, _IMAGE) for a in tt_plan["anchors"]}
        inputs["ready"] = {n: _fetch(tt["ready_segments"][n], work_dir, f"ready_{n}", log, _VIDEO)
                           for n in tt_plan["reuse"]}
    heartbeat.progress = 3

    if mode == "upscale" and (upscale.get("method") or "lanczos").lower() == "lanczos":
        # Pure ffmpeg: no ComfyUI, no TTS pause, no GPU.
        out_local = _upscale_clip(jid, inputs["source"], upscale, work_dir, heartbeat, cancel_check,
                                  deadline, os.path.join(work_dir, "video_gen-upscaled.mp4"), log)
        heartbeat.progress = 95
        return out_local, "mp4", "video/mp4"
    if mode == "turntable" and not tt_plan["generate"]:
        # Assembly of approved segments: join, remap, RIFE, encode. No ComfyUI, no TTS pause.
        opts = dict(tt, anchor_local={}, ready_local=inputs["ready"])
        api = _TurntableApi(jid, work_dir, heartbeat, cancel_check, deadline, log)
        heartbeat.progress = 5
        res = turntable_flow.run(opts, api, log)
        _upload_turntable_sidecars(jid, res, log)
        log(f"turntable assembled: {res['frames']} frames at {res['fps']} fps from {res['order']}; defects: {res['defects'] or 'none'}")
        heartbeat.progress = 95
        return res["video"], "mp4", "video/mp4"

    # 2. Server up (lazy start), TTS workers out of the way
    db.set_phase(jid, "starting comfyui", 3)
    comfy_client.ensure_server(log)
    with tts_guard.paused(log):
        try:
            stats = comfy_client.system_stats()
            dev = (stats.get("devices") or [{}])[0]
            log(f"comfyui {stats.get('system', {}).get('comfyui_version')} on {dev.get('name')} "
                f"vram_free={dev.get('vram_free', 0) // (1 << 20)} MiB")
        except Exception as e:  # noqa: BLE001 - telemetry only
            log(f"system_stats unavailable: {e}")

        db.set_phase(jid, "uploading inputs", 5)
        names = {}
        for key, val in inputs.items():
            if key in ("source", "anchors", "ready"):
                continue  # source: uploaded per segment by _upscale_clip; anchors: padded first by the turntable flow
            if isinstance(val, list):
                names[key] = [comfy_client.upload_input(v) for v in val]
            else:
                names[key] = comfy_client.upload_input(val)

        try:
            if mode in graphs.GEN_MODES:
                graph, meta = graphs.build(mode, p, names, f"video_gen/{jid}")
                log(f"video_gen {mode} {meta['width']}x{meta['height']} {meta['length']}f (~{meta['seconds']}s) "
                    f"steps={meta['steps']} turbo={meta['turbo']} seed={meta['seed']} family={meta['family']}")
                heartbeat.progress = 8
                up_secs = estimate.upscale_seconds(upscale, meta["seconds"]) if upscale else 0.0
                base_local = _run_prompt(jid, graph, "generate", heartbeat, cancel_check, deadline,
                                         os.path.join(work_dir, "video_gen.mp4"), log,
                                         prange=(8, 55 if upscale else 90), hint=estimate.sampling_hint(p, mode),
                                         after_seconds=up_secs, after_text=" - then upscale" if upscale else "")
                out_local = base_local
                if upscale:
                    # Free H3 before SeedVR2 so the two never share the 16 GB.
                    comfy_client.free()
                    heartbeat.progress = 55
                    # The base clip goes up BEFORE the upscale is attempted, matte-proof-sheet
                    # style: if SeedVR2 fails the job fails, but the generated video is not
                    # lost and the platform can still fetch outputs/<jid>-base.mp4.
                    db.set_phase(jid, "uploading base clip", 55)
                    try:
                        remote = db.upload_file(f"outputs/{jid}-base.mp4", base_local, "video/mp4")
                        log(f"base clip -> {remote}")
                    except Exception as exc:  # noqa: BLE001
                        log(f"base clip upload failed (continuing to upscale): {exc}")
                    db.set_phase(jid, "upscale: preparing", 56)
                    out_local = _upscale_clip(jid, base_local, upscale, work_dir, heartbeat, cancel_check,
                                              deadline, os.path.join(work_dir, "video_gen-upscaled.mp4"), log)
            elif mode == "turntable":
                opts = dict(tt, anchor_local=inputs["anchors"], ready_local=inputs["ready"])
                api = _TurntableApi(jid, work_dir, heartbeat, cancel_check, deadline, log)
                heartbeat.progress = 5
                res = turntable_flow.run(opts, api, log)
                out_local = res["video"]
                _upload_turntable_sidecars(jid, res, log)
                log(f"turntable done: {res['frames']} frames at {res['fps']} fps, segments {res['order']}, "
                    f"{'loops' if res['loops'] else 'partial'}; defects: {res['defects'] or 'none'}")
            else:
                heartbeat.progress = 8
                out_local = _upscale_clip(jid, inputs["source"], upscale, work_dir, heartbeat, cancel_check,
                                          deadline, os.path.join(work_dir, "video_gen-upscaled.mp4"), log)
        finally:
            # Hand the card back whether we succeeded, failed or were canceled.
            comfy_client.free()

    heartbeat.progress = 95
    # run_job uploads to outputs/<jid>.mp4 and writes output_path / signed_url
    # on the row, exactly like every other engine.
    return out_local, "mp4", "video/mp4"
